[package]
name = "simple_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
discorsd = { path = "../discorsd/discorsd" }
command_data_derive = { path = "../discorsd/command_data_derive" }
tokio = { version = "1.29.0", features=["macros"] }
chrono = "0.4.28"